spring.application.name: uservices/butelkatr

logging:
  pattern:
    level: '%clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %5p'

server:
  port: 9094

spring.cloud.zookeeper.discovery.root: /pl
spring.cloud.zookeeper:
  # prefix is not working ATM - it's not combining the uservices/${spring.application.name}
  prefix: uservices/
  dependencies:
    prezentatr:
      path: prezentatr